baseurl = "https://example.org/"
languageCode = "en-us"
title = "Karim Mezhoud"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "Karim Mezhoud"
	description = "A material design theme for documentations."
	copyright = "Released under the MIT license"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/kmezhoud/"

	version = "1.0.0"
	logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "blue"
    	accent  = "teal"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = ""
	github  = "kmezhoud"
	email   = "kmezhoud@gmail.com"


[[menu.main]]
	name   = "Material"
	url    = "/"
	weight = 0


[[menu.main]]
	name   = "Roadmap"
	url    = "roadmap/"
	weight = 30


[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
